3:
  class_type: CheckpointLoaderSimple
  inputs:
    ckpt_name: uncannyValley_ilxl10Noob.safetensors  # Default, overridden
4:
  class_type: EmptyLatentImage
  inputs:
    width: 512  # Changed to match bot's logic
    height: 512 # Changed to match bot's logic
    batch_size: 1
5:
  class_type: CLIPTextEncode
  inputs:
    text: ""  # Positive prompt
    clip: ["3", 1]
6:
  class_type: CLIPTextEncode
  inputs:
    text: ""  # Negative prompt
    clip: ["3", 1]
7:
  class_type: KSampler
  inputs:
    seed: 0  # Randomized by bot
    steps: 35
    cfg: 4.0
    sampler_name: dpmpp_2m_sde
    scheduler: exponential
    denoise: 1.0
    model: ["3", 0]
    positive: ["5", 0]
    negative: ["6", 0]
    latent_image: ["4", 0]
8:
  class_type: VAEDecode
  inputs:
    samples: ["7", 0]
    vae: ["3", 2]
9:
  class_type: SaveImage
  inputs:
    images: ["8", 0]
    filename_prefix: animate