3:
  class_type: KSampler
  inputs:
    seed: 0
    steps: 35
    cfg: 4
    sampler_name: dpmpp_2m_sde
    scheduler: exponential
    denoise: 1.0
    model: ["4", 0]
    positive: ["6", 0]
    negative: ["7", 0]
    latent_image: ["5", 0]
4:
  class_type: CheckpointLoaderSimple
  inputs:
    ckpt_name: uncannyValley_ilxl10Noob.safetensors  # Default, overridden by bot
5:
  class_type: EmptyLatentImage
  inputs:
    width: 1024  # Updated to match STATIC_WIDTH
    height: 1024 # Updated to match STATIC_HEIGHT
    batch_size: 1
6:
  class_type: CLIPTextEncode
  inputs:
    text: ""
    clip: ["4", 1]
7:
  class_type: CLIPTextEncode
  inputs:
    text: ""
    clip: ["4", 1]
8:
  class_type: VAEDecode
  inputs:
    samples: ["3", 0]
    vae: ["4", 2]
9:
  class_type: SaveImage
  inputs:
    images: ["8", 0]
    filename_prefix: txt2img